### ISSUE TITLE
FluentQuery - complex example

### ISSUE THREAD

**Issue by iNenadnano** [MihaelIsaev/SwifQL#1]
Hello @MihaelIsaev. Would you be so kind to demonstrate how one could do the exact thing as shown in [example 4](https://github.com/MihaelIsaev/FluentQuery#4-complex) of FluentQuery using SwifQL?

Thanks!

**Comment by MihaelIsaev** [comment]
Sure, thanks for asking 🙂 

```swift
func getListOfCars(_ req: Request) throws -> Future<[PublicCar]> {
    return SwifQLSelectBuilder()
        .select(Distinct(\Car.id))
        .select(\Car.year => "year")
        .select(\Car.color => "color")
        .select(\Car.engineCapacity => "engineCapacity")
        .select(|SwifQL.select(Fn.to_jsonb(Brand.table))| => "brand")
        .select(|SwifQL.select(Fn.to_jsonb(Model.table))| => "model")
        .select(|SwifQL.select(Fn.to_jsonb(BodyType.table))| => "bodyType")
        .select(|SwifQL.select(Fn.to_jsonb(EngineType.table))| => "engineType")
        .select(|SwifQL.select(Fn.to_jsonb(GearboxType.table))| => "gearboxType")
        .from(Car.table)
        .join(.left, Brand.table, on: \Brand.id == \Car.idBrand)
        .join(.left, Model.table, on: \Model.id == \Car.idModel)
        .join(.left, BodyType.table, on: \BodyType.id == \Car.idBodyType)
        .join(.left, EngineType.table, on: \EngineType.id == \Car.idEngineType)
        .join(.left, GearboxType.table, on: \GearboxType.id == \Car.idGearboxType)
        .groupBy(\Car.id, \Brand.id, \Model.id, \BodyType.id, \EngineType.id, \GearboxType.id)
        .orderBy(.asc(\Brand.value), .asc(\Model.value))
        .build()
        .execute(on: req, as: .psql) // or .mysql
        .all(decoding: PublicCar.self)
  }
}
```

as you can see the biggest difference is that there no more magic `.row()` function, instead of it you should write the whole magic code by yourself 🙂 

```swift
|SwifQL.select(Fn.to_jsonb(Brand.table))|
```
it will build
```sql
(SELECT to_jsonb("Brand"))
```

But you could write a little object for "magic" functions like `.row()` if you'd like to avoid writing this kind of complex code every time, e.g. like this:
```swift
struct MagicFn {
    static func row(_ item: SwifQLable) -> SwifQLable {
        return |SwifQL.select(Fn.to_jsonb(item))|
    }
}
```

so then you will be able to replace
```swift
.select(|SwifQL.select(Fn.to_jsonb(Brand.table))| => "brand")
```
with just
```swift
.select(MagicFn.row(Brand.table) => "brand")
```

P.S. I thought to add `MagicFn` struct into the lib, but it's not universal thing, I mean that mysql doesn't support this kind of thing, so I should create `MagicPgFn` struct instead, and also `MagicMySQLFn` struct as well 🙂 and more than that in my example `.row` uses `to_jsonb` function, but someone may expect `to_json` instead... and so on.. so in the end we will have no less wordy magic helpers than writing pure query code 🙂 and also writing query code without magic by yourself will help you a lot in a future complex cases I believe. 🙂

**Comment by iNenadnano** [comment]
Thanks a lot @MihaelIsaev for detailed explanation! Much appreciated!
